version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: marvel-user-api
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - secret_key=placeholder
      - mongodb_url=placeholder
      - secure_keyword=placeholder
    volumes:
      - .:/app
    ports:
      - "8000:8000"
